"""Oracle test: ferritin AMBER96 energy vs BALL Julia (BiochemicalAlgorithms.jl).

Compares energy components on crambin (1crn) without reconstruction,
to isolate the energy computation from the preparation pipeline.

BALL reports in kJ/mol; ferritin reports in kcal/mol (factor: 4.184).

Expected matches (same formula, same params, same atoms):
- Bond stretch: < 5% after unit conversion
- Angle bend: < 5% after unit conversion
- Electrostatic: < 5% after unit conversion

Expected differences (different topology building):
- Torsion: ~17% (different bond detection → different torsion list)
- VdW: large (different exclusion lists → different pair counting)
- Improper: different assignment rules

These differences are from topology building (distance vs template bonds),
not from the energy functions themselves.
"""

import os
import pytest
import ferritin

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CRAMBIN = os.path.join(REPO, "test-pdbs", "1crn.pdb")

KCAL_TO_KJ = 4.184

# BALL Julia reference values (kJ/mol) on raw 1crn.pdb (no reconstruction).
# Generated by: julia --project=BALL ball_energy_raw.jl test-pdbs/1crn.pdb
BALL_CRAMBIN_RAW = {
    "bond_stretch": 354.891,
    "angle_bend": 282.121,
    "torsion": 703.171,
    "improper_torsion": 2.077,
    "vdw": -425.372,
    "electrostatic": 80370.97,
}


class TestBallEnergyOracle:
    """Compare ferritin AMBER96 energy against BALL Julia reference."""

    @pytest.fixture
    def crambin_energy(self):
        s = ferritin.load(CRAMBIN)
        return ferritin.compute_energy(s, ff="amber96")

    def test_bond_stretch_matches(self, crambin_energy):
        fe_kj = crambin_energy["bond_stretch"] * KCAL_TO_KJ
        ball = BALL_CRAMBIN_RAW["bond_stretch"]
        pct = abs(fe_kj - ball) / ball * 100
        assert pct < 5, f"Bond stretch: {fe_kj:.2f} vs BALL {ball:.2f} ({pct:.1f}%)"

    def test_angle_bend_matches(self, crambin_energy):
        fe_kj = crambin_energy["angle_bend"] * KCAL_TO_KJ
        ball = BALL_CRAMBIN_RAW["angle_bend"]
        pct = abs(fe_kj - ball) / ball * 100
        assert pct < 5, f"Angle bend: {fe_kj:.2f} vs BALL {ball:.2f} ({pct:.1f}%)"

    def test_electrostatic_matches(self, crambin_energy):
        fe_kj = crambin_energy["electrostatic"] * KCAL_TO_KJ
        ball = BALL_CRAMBIN_RAW["electrostatic"]
        pct = abs(fe_kj - ball) / abs(ball) * 100
        assert pct < 5, f"Electrostatic: {fe_kj:.2f} vs BALL {ball:.2f} ({pct:.1f}%)"

    def test_torsion_order_of_magnitude(self, crambin_energy):
        """Torsion differs ~17% due to different bond detection.
        Just verify it's the right order of magnitude."""
        fe_kj = crambin_energy["torsion"] * KCAL_TO_KJ
        ball = BALL_CRAMBIN_RAW["torsion"]
        pct = abs(fe_kj - ball) / ball * 100
        assert pct < 50, f"Torsion: {fe_kj:.2f} vs BALL {ball:.2f} ({pct:.1f}%)"

    def test_all_components_finite(self, crambin_energy):
        import numpy as np
        for key in ["bond_stretch", "angle_bend", "torsion", "improper_torsion",
                     "vdw", "electrostatic", "total"]:
            assert np.isfinite(crambin_energy[key]), f"{key} is not finite"

    def test_total_is_sum(self, crambin_energy):
        expected = sum(crambin_energy[k] for k in [
            "bond_stretch", "angle_bend", "torsion", "improper_torsion",
            "vdw", "electrostatic", "solvation",
        ])
        assert abs(crambin_energy["total"] - expected) < 0.01
