"""Oracle test: ferritin AMBER96 energy vs BALL Julia (BiochemicalAlgorithms.jl).

Compares energy components on crambin (1crn) without reconstruction,
validating the energy computation, topology building, and charge assignment.

Both ferritin and BALL output in kJ/mol.

Bonded + nonbonded components match BALL to <0.1% (2026-04-13 onwards).
The improper term is the one meaningful divergence.

Improper (post 2026-04-13 double-wildcard fix):
- BALL: 10 impropers, 2.077 kJ/mol
- Ferritin: 125 impropers, ~8.1 kJ/mol
- OpenMM amber96 agrees with ferritin within 0.5%, so ferritin's number
  is the AMBER-canonical value.

Root cause of the gap: BALL's improper-torsion matcher supports only
single-wildcard atom-type patterns, while the AMBER spec requires
double-wildcard (e.g. `* * N H` for the amide-plane improper). BALL
therefore misses ~100 amide-plane impropers on crambin — one at every
peptide N-H — and scales linearly with chain length. See
`params.rs::get_improper_torsion` for ferritin's AMBER-spec matcher.

The test below asserts ferritin >= BALL as a regression guard, so
the double-wildcard matcher stays in place until BALL gains the
same capability.
"""

import os
import pytest
import ferritin

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CRAMBIN = os.path.join(REPO, "test-pdbs", "1crn.pdb")

# BALL Julia reference values (kJ/mol) on raw 1crn.pdb (no reconstruction).
# Generated by: julia --project=BALL ball_energy_raw.jl test-pdbs/1crn.pdb
# BALL uses: normalize_names! + build_bonds! + AmberFF (terminal variants)
BALL_CRAMBIN_RAW = {
    "bond_stretch": 354.891,
    "angle_bend": 282.121,
    "torsion": 703.171,
    "improper_torsion": 2.077,
    "vdw": -425.372,
    "electrostatic": 80370.97,
}


class TestBallEnergyOracle:
    """Compare ferritin AMBER96 energy against BALL Julia reference."""

    @pytest.fixture
    def crambin_energy(self):
        s = ferritin.load(CRAMBIN)
        return ferritin.compute_energy(s, ff="amber96")  # default kJ/mol

    def test_bond_stretch_matches(self, crambin_energy):
        fe = crambin_energy["bond_stretch"]
        ball = BALL_CRAMBIN_RAW["bond_stretch"]
        pct = abs(fe - ball) / ball * 100
        assert pct < 0.1, f"Bond stretch: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_angle_bend_matches(self, crambin_energy):
        fe = crambin_energy["angle_bend"]
        ball = BALL_CRAMBIN_RAW["angle_bend"]
        pct = abs(fe - ball) / ball * 100
        assert pct < 0.1, f"Angle bend: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_torsion_matches(self, crambin_energy):
        fe = crambin_energy["torsion"]
        ball = BALL_CRAMBIN_RAW["torsion"]
        pct = abs(fe - ball) / ball * 100
        assert pct < 0.1, f"Torsion: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_vdw_matches(self, crambin_energy):
        fe = crambin_energy["vdw"]
        ball = BALL_CRAMBIN_RAW["vdw"]
        pct = abs(fe - ball) / abs(ball) * 100
        assert pct < 0.1, f"VdW: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_electrostatic_matches(self, crambin_energy):
        fe = crambin_energy["electrostatic"]
        ball = BALL_CRAMBIN_RAW["electrostatic"]
        pct = abs(fe - ball) / abs(ball) * 100
        assert pct < 0.1, f"Electrostatic: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_improper_on_same_order_as_ball(self, crambin_energy):
        """Improper is a small term; ferritin's number is expected to exceed
        BALL's because ferritin enforces AMBER's full double-wildcard
        improper lookup (see params.rs::get_improper_torsion) and thus
        catches the ~100 amide-plane impropers (`* * N H`) that BALL's
        single-wildcard implementation misses on every peptide bond.

        Before the 2026-04-13 double-wildcard fix: ferritin had 15
        impropers = 2.2 kJ/mol, close to BALL's 2.08 kJ/mol.
        After the fix: 125 impropers = 8.1 kJ/mol, which is the AMBER-
        canonical value (OpenMM's amber96 agrees within 0.5%).

        We still assert the absolute magnitude is small so this term
        doesn't quietly explode.
        """
        fe = crambin_energy["improper_torsion"]
        ball = BALL_CRAMBIN_RAW["improper_torsion"]
        # Ferritin expected > BALL but still small in magnitude.
        assert 0 < fe < 20, f"Improper ferritin: {fe:.2f} kJ/mol (expected 2-15)"
        # Historical expectation: BALL was ~2 kJ/mol. We should be above that.
        assert fe >= ball, (
            f"Improper regressed below BALL: {fe:.2f} < BALL {ball:.2f}. "
            "Double-wildcard improper matching should catch more amide-plane "
            "terms than BALL's single-wildcard implementation."
        )

    def test_all_components_finite(self, crambin_energy):
        import numpy as np
        for key in ["bond_stretch", "angle_bend", "torsion", "improper_torsion",
                     "vdw", "electrostatic", "total"]:
            assert np.isfinite(crambin_energy[key]), f"{key} is not finite"

    def test_total_is_sum(self, crambin_energy):
        expected = sum(crambin_energy[k] for k in [
            "bond_stretch", "angle_bend", "torsion", "improper_torsion",
            "vdw", "electrostatic", "solvation",
        ])
        assert abs(crambin_energy["total"] - expected) < 0.1  # kJ/mol tolerance
