"""Oracle test: ferritin AMBER96 energy vs BALL Julia (BiochemicalAlgorithms.jl).

Compares energy components on crambin (1crn) without reconstruction,
validating the energy computation, topology building, and charge assignment.

Both ferritin and BALL output in kJ/mol.

Results (2026-04-09):
- Bond stretch: 0.00% match
- Angle bend: 0.00% match
- Torsion: 0.00% match
- VdW: 0.00% match
- Electrostatic: 0.02% match
- Improper: +6.5% (ferritin has 15 impropers, BALL has 10)

The improper difference is from 5 extra physically-correct impropers that
ferritin assigns (carboxylate planarity for ASP/GLU/ASN-C, hydroxyl planarity
for TYR:CZ). BALL misses these due to its permutation iteration order not
placing atom types in positions that match the *-O2-C-O2 parameter. The
absolute energy difference is 0.13 kJ/mol — negligible.
"""

import os
import pytest
import ferritin

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CRAMBIN = os.path.join(REPO, "test-pdbs", "1crn.pdb")

# BALL Julia reference values (kJ/mol) on raw 1crn.pdb (no reconstruction).
# Generated by: julia --project=BALL ball_energy_raw.jl test-pdbs/1crn.pdb
# BALL uses: normalize_names! + build_bonds! + AmberFF (terminal variants)
BALL_CRAMBIN_RAW = {
    "bond_stretch": 354.891,
    "angle_bend": 282.121,
    "torsion": 703.171,
    "improper_torsion": 2.077,
    "vdw": -425.372,
    "electrostatic": 80370.97,
}


class TestBallEnergyOracle:
    """Compare ferritin AMBER96 energy against BALL Julia reference."""

    @pytest.fixture
    def crambin_energy(self):
        s = ferritin.load(CRAMBIN)
        return ferritin.compute_energy(s, ff="amber96")  # default kJ/mol

    def test_bond_stretch_matches(self, crambin_energy):
        fe = crambin_energy["bond_stretch"]
        ball = BALL_CRAMBIN_RAW["bond_stretch"]
        pct = abs(fe - ball) / ball * 100
        assert pct < 0.1, f"Bond stretch: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_angle_bend_matches(self, crambin_energy):
        fe = crambin_energy["angle_bend"]
        ball = BALL_CRAMBIN_RAW["angle_bend"]
        pct = abs(fe - ball) / ball * 100
        assert pct < 0.1, f"Angle bend: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_torsion_matches(self, crambin_energy):
        fe = crambin_energy["torsion"]
        ball = BALL_CRAMBIN_RAW["torsion"]
        pct = abs(fe - ball) / ball * 100
        assert pct < 0.1, f"Torsion: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_vdw_matches(self, crambin_energy):
        fe = crambin_energy["vdw"]
        ball = BALL_CRAMBIN_RAW["vdw"]
        pct = abs(fe - ball) / abs(ball) * 100
        assert pct < 0.1, f"VdW: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_electrostatic_matches(self, crambin_energy):
        fe = crambin_energy["electrostatic"]
        ball = BALL_CRAMBIN_RAW["electrostatic"]
        pct = abs(fe - ball) / abs(ball) * 100
        assert pct < 0.1, f"Electrostatic: {fe:.2f} vs BALL {ball:.2f} ({pct:.4f}%)"

    def test_improper_order_of_magnitude(self, crambin_energy):
        """Improper torsion differs ~6.5% due to 5 extra correct impropers.

        Ferritin assigns carboxylate planarity (ASP:CG, GLU:CD, ASN-C:C)
        and TYR hydroxyl planarity (TYR:CZ) that BALL misses due to its
        permutation iteration order. Absolute difference: 0.13 kJ/mol.
        """
        fe = crambin_energy["improper_torsion"]
        ball = BALL_CRAMBIN_RAW["improper_torsion"]
        pct = abs(fe - ball) / ball * 100
        assert pct < 10, f"Improper: {fe:.2f} vs BALL {ball:.2f} ({pct:.1f}%)"

    def test_all_components_finite(self, crambin_energy):
        import numpy as np
        for key in ["bond_stretch", "angle_bend", "torsion", "improper_torsion",
                     "vdw", "electrostatic", "total"]:
            assert np.isfinite(crambin_energy[key]), f"{key} is not finite"

    def test_total_is_sum(self, crambin_energy):
        expected = sum(crambin_energy[k] for k in [
            "bond_stretch", "angle_bend", "torsion", "improper_torsion",
            "vdw", "electrostatic", "solvation",
        ])
        assert abs(crambin_energy["total"] - expected) < 0.1  # kJ/mol tolerance
