//! Xie analytic test-model parity vs NESSie (gold-standard bit-exact gate).
//!
//! Loads `fixtures/nessie/xie_dump.json` (generated by `tools/oracle/nessie/xie_dump.jl`)
//! and checks the Rust port's reaction-field energy, electrostatic potential, and
//! molecular potential against NESSie's own output for the local + two nonlocal models.

use proteon_core::surface::geom::Vec3;
use proteon_electrostatics::{
    analytic_sphere_mesh, rfenergy, scalemodel, solve_local_elements, Charge, Params, SolveConfig,
    Tri, XieKind, XieModel,
};

fn rel(a: f64, b: f64) -> f64 {
    (a - b).abs() / b.abs().max(1e-300)
}

#[test]
fn xie_local_validates_bem_multicharge() {
    // The Xie LOCAL model is the analytic local-Poisson solution for a MULTI-charge
    // sphere — an oracle the single-charge Born/Kirkwood gates can't provide. The BEM
    // local solve on the same geometry must match it (off-centre charges only, so the
    // analytic central-charge ε∞ branch is not involved). First multi-charge BEM gate.
    let (radius, eo, es) = (5.0, 1.0, 78.0);
    let raw = [
        Charge { pos: Vec3::new(1.0, 0.0, 0.0), val: 1.0 },
        Charge { pos: Vec3::new(-0.5, 0.6, 0.2), val: -1.0 },
        Charge { pos: Vec3::new(0.2, -0.7, 0.3), val: 0.5 },
    ];
    let scaled = scalemodel(&raw, radius, true);
    let xie = XieModel::new(XieKind::Local, radius, &raw, eo, es, 1.8, 20.0, 40).rfenergy();

    let mesh = analytic_sphere_mesh(radius, 4);
    let els: Vec<Tri> = mesh
        .tris
        .iter()
        .map(|t| Tri::new(mesh.verts[t[0] as usize], mesh.verts[t[1] as usize], mesh.verts[t[2] as usize]))
        .collect();
    let params = Params { eps_omega: eo, eps_sigma: es, eps_inf: 1.8, lambda: 20.0 };
    let cfg = SolveConfig { tol: 1e-9, ..Default::default() };
    let (res, _) = solve_local_elements(&els, &scaled, &params, &cfg).expect("solve");
    let bem = rfenergy(&els, &scaled, &res);

    let r = rel(bem, xie);
    eprintln!("multi-charge BEM {bem:.3} vs Xie-local {xie:.3} (rel {r:.3})");
    assert!(bem < 0.0 && xie < 0.0);
    assert!(r < 0.03, "BEM off Xie-local by {r:.3} (> 3%)");
}

#[test]
fn xie_models_match_nessie() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/nessie/xie_dump.json"
    ))
    .expect("fixture present");
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("valid json");

    for case in doc["cases"].as_array().unwrap() {
        let p = &case["params"];
        let (eo, es, ei, lam) = (
            p["eps_omega"].as_f64().unwrap(),
            p["eps_sigma"].as_f64().unwrap(),
            p["eps_inf"].as_f64().unwrap(),
            p["lambda"].as_f64().unwrap(),
        );
        let radius = case["radius"].as_f64().unwrap();
        let len = case["len"].as_u64().unwrap() as usize;
        let charges: Vec<Charge> = case["input_charges"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| {
                let pos = c["pos"].as_array().unwrap();
                Charge {
                    pos: Vec3::new(
                        pos[0].as_f64().unwrap(),
                        pos[1].as_f64().unwrap(),
                        pos[2].as_f64().unwrap(),
                    ),
                    val: c["val"].as_f64().unwrap(),
                }
            })
            .collect();
        let obs: Vec<Vec3> = case["obs_points"]
            .as_array()
            .unwrap()
            .iter()
            .map(|p| {
                let a = p.as_array().unwrap();
                Vec3::new(
                    a[0].as_f64().unwrap(),
                    a[1].as_f64().unwrap(),
                    a[2].as_f64().unwrap(),
                )
            })
            .collect();

        for (key, kind) in [
            ("local", XieKind::Local),
            ("nonlocal1", XieKind::Nonlocal1),
            ("nonlocal2", XieKind::Nonlocal2),
        ] {
            let model = XieModel::new(kind, radius, &charges, eo, es, ei, lam, len);
            let block = &case[key];

            let want_e = block["rfenergy"].as_f64().unwrap();
            let got_e = model.rfenergy();
            assert!(rel(got_e, want_e) < 1e-9, "{key} rfenergy {got_e} vs {want_e}");

            let want_es = block["espotential"].as_array().unwrap();
            let want_mol = block["molpotential"].as_array().unwrap();
            for (i, xi) in obs.iter().enumerate() {
                let g_es = model.espotential(*xi);
                let w_es = want_es[i].as_f64().unwrap();
                assert!(rel(g_es, w_es) < 1e-8, "{key} espot[{i}] {g_es} vs {w_es}");
                let g_mol = model.molpotential(*xi);
                let w_mol = want_mol[i].as_f64().unwrap();
                assert!(rel(g_mol, w_mol) < 1e-8, "{key} molpot[{i}] {g_mol} vs {w_mol}");
            }
        }
    }
}
