"""Build a biological assembly from a PDB ASU + REMARK 350 BIOMT operators.

PR1 of the assembly builder (``devdocs/ASSEMBLY_BUILDER_DESIGN.md``): the
*materialization* layer. It applies the REMARK 350 BIOMT operators of one
biomolecule to the applicable ASU chains, producing the assembled coordinates as
re-loadable PDB text plus a per-chain provenance map. It does NOT validate the
new inter-copy interfaces or export supervision — those are PR2 (re-prepare the
assembled structure through ``prepare``) and PR3 (interface export).

This unlocks the ``requires_assembly_expansion`` bucket: a monomeric / sub-ASU
whose biological assembly is generated by BIOMT (38% of a diverse sample). The
deposited ASU stays untouched; this builds the oligomer beside it.

Scope (PR1): identity + rigid BIOMT operators on protein/all ATOM+HETATM records
of the applicable chains; deterministic legal PDB chain IDs; operator dedup and
near-exact copy-overlap detection; loud failure when the copy count exceeds the
PDB chain-id space (mmCIF output is a follow-on). Biomolecule 1 by default.
"""

from __future__ import annotations

import io
import os
import tempfile
from dataclasses import dataclass, field
from typing import List, Optional, Union

import numpy as np

from .assembly import OperatorBlock, parse_remark_350

# PDB fixed-column slices (0-based) for ATOM/HETATM records.
_SERIAL = slice(6, 11)
_CHAIN_COL = 21
#: PDB atom serial field is 5 digits — assemblies past this can't be a valid PDB.
_MAX_PDB_SERIAL = 99999
#: PDB coordinate fields are 8 chars at 3 decimals (%8.3f): valid [-999.999,
#: 9999.999]. A transform moving an atom outside this overflows the fixed columns.
_PDB_COORD_MIN = -999.999
_PDB_COORD_MAX = 9999.999
_X = slice(30, 38)
_Y = slice(38, 46)
_Z = slice(46, 54)

#: Legal single-character PDB chain ids, in a deterministic assignment order.
_CHAIN_ALPHABET = (
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789"
)

#: Two operators are duplicates when every matrix entry is within this (Å / unit).
_OP_DEDUP_TOL = 1e-3
#: A transformed copy that lands within this RMSD of an already-placed copy of the
#: same source chain is a redundant / coincident operator, not a new interface.
_OVERLAP_RMSD_TOL = 0.5  # Å


@dataclass
class AssemblyChain:
    """Provenance for one chain in the built assembly."""

    assembled_chain_id: str
    source_chain_id: str
    operator_index: int
    is_identity: bool


@dataclass
class BuiltAssembly:
    """A materialized biological assembly (PR1): re-loadable text + provenance."""

    pdb_text: str
    chains: List[AssemblyChain] = field(default_factory=list)
    n_operators: int = 0
    n_source_chains: int = 0
    biomolecule_id: Optional[int] = None

    @property
    def n_chains(self) -> int:
        return len(self.chains)

    def __repr__(self) -> str:
        return (
            f"BuiltAssembly(biomolecule={self.biomolecule_id}, "
            f"operators={self.n_operators}, source_chains={self.n_source_chains}, "
            f"chains={self.n_chains}, {len(self.pdb_text)} chars)"
        )

    def load(self):
        """Load the assembled coordinates as a proteon Structure (via a temp file,
        since the loader is path-based). Ready for PR2's re-prepare."""
        from .io import load_pdb

        with tempfile.NamedTemporaryFile("w", suffix=".pdb", delete=False) as fh:
            fh.write(self.pdb_text)
            tmp = fh.name
        try:
            return load_pdb(tmp)
        finally:
            os.unlink(tmp)


def _op_matrix(op):
    """(R 3x3, t 3) from a REMARK 350 3x4 row-major operator."""
    r = np.array([[op[i][j] for j in range(3)] for i in range(3)], dtype=np.float64)
    t = np.array([op[i][3] for i in range(3)], dtype=np.float64)
    return r, t


def _is_identity(r, t):
    return np.allclose(r, np.eye(3), atol=_OP_DEDUP_TOL) and np.allclose(t, 0.0, atol=_OP_DEDUP_TOL)


def _dedup_operators(operators):
    """Drop operators whose (R, t) duplicate an earlier one (keep first).

    Returns ``(orig_index, R, t)`` — ``orig_index`` is the 0-based position in the
    block's REMARK 350 operator list, preserved so provenance maps an assembled
    chain back to the deposited BIOMT record despite dedup/sort reordering.
    """
    kept = []
    for idx, op in enumerate(operators):
        r, t = _op_matrix(op)
        if any(np.allclose(r, kr, atol=_OP_DEDUP_TOL) and np.allclose(t, kt, atol=_OP_DEDUP_TOL)
               for _i, kr, kt in kept):
            continue
        kept.append((idx, r, t))
    return kept


def _atom_lines_for_chains(text, chains):
    """ATOM/HETATM record lines whose chain id is in `chains` (model 1 only)."""
    wanted = set(chains)
    out, in_model = [], True
    for line in text.splitlines():
        rec = line[:6]
        if rec == "MODEL ":
            # Only the first model; stop collecting after ENDMDL of model 1.
            in_model = line.split()[1] == "1" if len(line.split()) > 1 else True
        elif rec == "ENDMDL":
            in_model = False
        elif in_model and rec in ("ATOM  ", "HETATM"):
            cid = line[_CHAIN_COL] if len(line) > _CHAIN_COL else " "
            if cid in wanted or (cid == " " and "" in wanted):
                out.append(line)
    return out


def _transform_line(line, r, t, new_chain, serial):
    """Apply (R, t) to a PDB ATOM line's xyz, set its chain id, and renumber its
    atom serial (each copy needs unique serials for a valid, re-loadable PDB)."""
    xyz = np.array([float(line[_X]), float(line[_Y]), float(line[_Z])])
    nx, ny, nz = r @ xyz + t
    line = line.ljust(80)
    body = (
        line[:_SERIAL.start] + f"{serial:5d}" + line[_SERIAL.stop:_CHAIN_COL]
        + new_chain + line[_CHAIN_COL + 1:30]
        + f"{nx:8.3f}{ny:8.3f}{nz:8.3f}" + line[54:]
    )
    return body.rstrip()


def build_assembly(
    path_or_text: Union[str, os.PathLike], *, biomolecule: int = 1
) -> Union[BuiltAssembly, str]:
    """Build biomolecule ``biomolecule`` from a PDB's REMARK 350 BIOMT operators.

    Returns a :class:`BuiltAssembly`, or a distinct drop-reason string:
    ``"no_assembly_metadata"`` (no usable REMARK 350), ``"biomolecule_not_found"``,
    ``"assembly_too_large_for_pdb"`` (copy count exceeds the 62 legal chain ids —
    mmCIF output is a follow-on). Never raises on these.
    """
    text = _read(path_or_text)
    bios = parse_remark_350(text)
    if not bios:
        return "no_assembly_metadata"
    bio = next((b for b in bios if b.id == biomolecule), None)
    if bio is None or not bio.operators:
        return "biomolecule_not_found"

    # Per-block (chains, operators): each block's operators apply ONLY to its own
    # chains, not all-to-all (codex). `bio.blocks` preserves the association; older
    # single-block records collapse to one block via the flattened views.
    blocks = bio.blocks or [OperatorBlock(chains=bio.chains, operators=bio.operators)]

    chain_lines: dict = {}
    candidates = []  # (ident, src, op_idx, r, t) across ALL blocks
    n_ops_total = 0
    for blk in blocks:
        ops = _dedup_operators(blk.operators)
        n_ops_total += len(ops)
        present = []
        for c in blk.chains:
            if c not in chain_lines:
                ls = _atom_lines_for_chains(text, [c])
                if ls:
                    chain_lines[c] = ls
            if c in chain_lines:
                present.append(c)
        for op_idx, r, t in ops:
            ident = _is_identity(r, t)
            for src in present:
                candidates.append((ident, src, op_idx, r, t))
    if not chain_lines:
        return "no_assembly_metadata"

    # Place ALL identity copies first (across every block), THEN expansions, so the
    # redundant-overlap skip never drops a real ASU identity copy in favour of an
    # earlier block's expansion that happened to land on it (codex). The overlap
    # check compares against ALL placed copies of ANY chain (an operator can map
    # one listed chain onto another's deposited position); the shape guard means
    # only identical-size chains can coincide. Collected BEFORE the PDB-limit check
    # so redundant operators that collapse don't trip the limit (codex).
    candidates.sort(key=lambda c: not c[0])  # identities (ident=True) first
    placed = []  # all placed copies' coords (any chain)
    copies = []  # (r, t, ident, src, op_idx, lines, moved)
    for ident, src, op_idx, r, t in candidates:
        lines = chain_lines[src]
        coords = np.array([[float(l[_X]), float(l[_Y]), float(l[_Z])] for l in lines])
        moved = coords @ r.T + t
        if any(
            prev.shape == moved.shape
            and np.sqrt(((prev - moved) ** 2).sum(axis=1).mean()) < _OVERLAP_RMSD_TOL
            for prev in placed
        ):
            continue
        placed.append(moved)
        copies.append((r, t, ident, src, op_idx, lines, moved))

    # PDB serial field is 5 digits — too many atoms can't be a valid PDB (the
    # chain-id capacity is checked exactly during id assignment below, so a
    # preserved blank-chain identity plus a full 62-letter alphabet still fits).
    n_atoms = sum(len(lines) for *_x, lines, _m in copies)
    if n_atoms > _MAX_PDB_SERIAL:
        return "assembly_too_large_for_pdb"
    # A transform can move atoms outside the fixed-width PDB coordinate fields
    # (%8.3f) — that would overflow the columns and break re-loadability, so fail
    # loud rather than emit malformed text (codex; mmCIF output is a follow-on).
    for *_x, _m in copies:
        if _m.size and (_m.min() < _PDB_COORD_MIN or _m.max() > _PDB_COORD_MAX):
            return "assembly_coords_exceed_pdb"

    # Pass 1: identity copies claim their deposited chain id (a legal letter, or a
    # blank chain as a space) so an identity-only assembly reproduces the ASU ids.
    # Pass 2: everything else gets the next free synthetic id.
    used: set = set()
    cids = [None] * len(copies)
    for i, (_r, _t, ident, src, _op, _ln, _m) in enumerate(copies):
        deposited = src if src else " "  # blank chain id -> space (valid in PDB)
        if ident and (deposited in _CHAIN_ALPHABET or deposited == " ") and deposited not in used:
            cids[i] = deposited
            used.add(deposited)
    free = (ch for ch in _CHAIN_ALPHABET if ch not in used)
    for i in range(len(copies)):
        if cids[i] is None:
            cids[i] = next(free, None)
            if cids[i] is None:  # ran out of legal PDB chain ids (mmCIF follow-on)
                return "assembly_too_large_for_pdb"

    emitted, provenance, serial = [], [], 0
    for (r, t, ident, src, op_idx, lines, _m), cid in zip(copies, cids):
        for ln in lines:
            serial += 1
            emitted.append(_transform_line(ln, r, t, cid, serial))
        provenance.append(AssemblyChain(cid, src, op_idx, ident))

    pdb_text = "\n".join(emitted) + "\nEND\n"
    return BuiltAssembly(
        pdb_text=pdb_text,
        chains=provenance,
        n_operators=n_ops_total,
        n_source_chains=len(chain_lines),
        biomolecule_id=biomolecule,
    )


def _read(path_or_text) -> str:
    s = str(path_or_text)
    if "\n" in s or s.startswith(("ATOM", "HEADER", "REMARK")):
        return s
    with io.open(s, "r") as fh:
        return fh.read()
