"""Build a biological assembly from a PDB ASU + REMARK 350 BIOMT operators.

PR1 of the assembly builder (``devdocs/ASSEMBLY_BUILDER_DESIGN.md``): the
*materialization* layer. It applies the REMARK 350 BIOMT operators of one
biomolecule to the applicable ASU chains, producing the assembled coordinates as
re-loadable PDB text plus a per-chain provenance map. It does NOT validate the
new inter-copy interfaces or export supervision — those are PR2 (re-prepare the
assembled structure through ``prepare``) and PR3 (interface export).

This unlocks the ``requires_assembly_expansion`` bucket: a monomeric / sub-ASU
whose biological assembly is generated by BIOMT (38% of a diverse sample). The
deposited ASU stays untouched; this builds the oligomer beside it.

Scope (PR1): identity + rigid BIOMT operators on protein/all ATOM+HETATM records
of the applicable chains; deterministic legal PDB chain IDs; operator dedup and
near-exact copy-overlap detection; loud failure when the copy count exceeds the
PDB chain-id space (mmCIF output is a follow-on). Biomolecule 1 by default.
"""

from __future__ import annotations

import io
import os
import tempfile
from dataclasses import dataclass, field
from typing import List, Optional, Union

import numpy as np

from .assembly import OperatorBlock, parse_remark_350

# PDB fixed-column slices (0-based) for ATOM/HETATM records.
_SERIAL = slice(6, 11)
_CHAIN_COL = 21
#: PDB atom serial field is 5 digits — assemblies past this can't be a valid PDB.
_MAX_PDB_SERIAL = 99999
#: PDB coordinate fields are 8 chars at 3 decimals (%8.3f): valid [-999.999,
#: 9999.999]. A transform moving an atom outside this overflows the fixed columns.
_PDB_COORD_MIN = -999.999
_PDB_COORD_MAX = 9999.999
_X = slice(30, 38)
_Y = slice(38, 46)
_Z = slice(46, 54)

#: Legal single-character PDB chain ids, in a deterministic assignment order.
_CHAIN_ALPHABET = (
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789"
)

#: Two operators are duplicates when every matrix entry is within this (Å / unit).
_OP_DEDUP_TOL = 1e-3
#: A transformed copy that lands within this RMSD of an already-placed copy of the
#: same source chain is a redundant / coincident operator, not a new interface.
_OVERLAP_RMSD_TOL = 0.5  # Å


@dataclass
class AssemblyChain:
    """Provenance for one chain in the built assembly."""

    assembled_chain_id: str
    source_chain_id: str
    operator_index: int
    is_identity: bool


@dataclass(init=False)
class BuiltAssembly:
    """A materialized biological assembly: re-loadable text + provenance.

    ``format`` is ``"pdb"`` when the assembly fits PDB's limits (≤62 chains,
    ≤99,999 atoms, coords within ±9999.999 Å) or ``"mmcif"`` for the larger
    assemblies PDB can't represent (capsids, big oligomers). ``text`` is the
    serialized structure; ``load()`` dispatches to the right loader.
    """

    text: str
    format: str
    chains: List[AssemblyChain]
    n_operators: int
    n_source_chains: int
    biomolecule_id: Optional[int]

    def __init__(
        self,
        text: Optional[str] = None,
        chains: Optional[List[AssemblyChain]] = None,
        n_operators: int = 0,
        n_source_chains: int = 0,
        biomolecule_id: Optional[int] = None,
        *,
        format: str = "pdb",
        pdb_text: Optional[str] = None,
    ):
        # Positional order preserved from the old dataclass `(pdb_text/text, chains,
        # n_operators, n_source_chains, biomolecule_id)`; `format` is keyword-only
        # so a legacy positional `BuiltAssembly(text, chains)` still binds `chains`
        # correctly (codex). `pdb_text` is the legacy text kwarg (always PDB).
        self.text = text if text is not None else (pdb_text or "")
        self.format = format
        self.chains = list(chains) if chains else []
        self.n_operators = n_operators
        self.n_source_chains = n_source_chains
        self.biomolecule_id = biomolecule_id

    @property
    def n_chains(self) -> int:
        return len(self.chains)

    @property
    def pdb_text(self) -> str:
        """The PDB text — only valid when ``format == "pdb"``. Raises for an
        mmCIF-backed assembly (callers must not feed mmCIF to a PDB parser); use
        ``.text`` / ``.load()`` instead."""
        if self.format != "pdb":
            raise ValueError(
                "this assembly is mmCIF-backed (too large for PDB); use .text or .load()"
            )
        return self.text

    def __repr__(self) -> str:
        return (
            f"BuiltAssembly(format={self.format}, biomolecule={self.biomolecule_id}, "
            f"operators={self.n_operators}, source_chains={self.n_source_chains}, "
            f"chains={self.n_chains}, {len(self.text)} chars)"
        )

    def load(self):
        """Load the assembled coordinates as a proteon Structure (via a temp file,
        since the loader is path-based), dispatching on ``format``."""
        from .io import load_mmcif, load_pdb

        suffix = ".cif" if self.format == "mmcif" else ".pdb"
        loader = load_mmcif if self.format == "mmcif" else load_pdb
        with tempfile.NamedTemporaryFile("w", suffix=suffix, delete=False) as fh:
            fh.write(self.text)
            tmp = fh.name
        try:
            return loader(tmp)
        finally:
            os.unlink(tmp)


@dataclass
class PreparedAssembly:
    """A built biological assembly, re-prepared so the NEW inter-copy interfaces
    are validated by the normal `prepare` scans (PR2).

    `report.n_heavy_clashes` / `clash_residue_indices` / `chirality_residue_indices`
    now cover the FULL assembly — including clashes that exist only between
    symmetry copies and were invisible to the deposited ASU's scan. Feed
    `structure` + `report` into `build_complex_supervision_examples` (PR3).
    """

    structure: object
    report: object
    chains: List[AssemblyChain] = field(default_factory=list)
    n_operators: int = 0
    biomolecule_id: Optional[int] = None

    @property
    def n_chains(self) -> int:
        return len(self.chains)


def prepare_assembly(
    path_or_text: Union[str, os.PathLike], *, biomolecule: int = 1, **prepare_kwargs
) -> Union[PreparedAssembly, str]:
    """Build biomolecule `biomolecule` from BIOMT and re-prepare it (PR2).

    Returns a :class:`PreparedAssembly` (the prepared assembled structure + a
    report whose clash/chirality scans cover the new inter-copy interfaces), or a
    materialization drop-reason string (see :func:`build_assembly`).

    `prepare_kwargs` is forwarded to :func:`proteon.prepare`; supervision callers
    typically pass ``reconstruct=False`` (don't fabricate atoms) and
    ``minimize=False`` (the clash/chirality gates are structural). The key
    property: a steric overlap that exists ONLY in the assembly is detected here,
    because the whole oligomer goes through the same clash scan as any structure.
    """
    built = build_assembly(path_or_text, biomolecule=biomolecule)
    if isinstance(built, str):
        return built  # materialization failed (no metadata / too large / etc.)
    from .prepare import prepare as _prepare

    structure = built.load()
    report = _prepare(structure, **prepare_kwargs)
    return PreparedAssembly(
        structure=structure,
        report=report,
        chains=built.chains,
        n_operators=built.n_operators,
        biomolecule_id=built.biomolecule_id,
    )


def build_assembly_supervision_examples(
    path_or_text: Union[str, os.PathLike],
    *,
    min_coverage: float,
    biomolecule: int = 1,
    profile: str = "heavy_coords",
    mask_untrustworthy_coords: bool = True,
    **prepare_kwargs,
):
    """Build a biological assembly from BIOMT and export it as label-safe interface
    supervision (PR3) — recovering the ``requires_assembly_expansion`` bucket.

    Pipeline: :func:`prepare_assembly` (build + re-prepare, validating the new
    inter-copy interfaces) → :func:`build_complex_supervision_examples` (the
    interface gate from #197: ≥2 chains, per-chain coverage, no unmasked hazard,
    masked per-chain examples). A BUILT assembly is the biological assembly *by
    construction* (all BIOMT operators applied), so ``assembly_is_asu`` is set
    ``True`` for the gate — unlike the deposited-ASU path, no REMARK 350 chain-set
    match is needed (we generated the chains).

    Returns a :class:`~proteon.supervision.ComplexSupervisionExamples`, or a
    drop-reason string (materialization reasons from :func:`build_assembly`, or the
    interface-gate reasons). Supervision callers pass ``reconstruct=False`` /
    ``minimize=False`` by convention; defaulted here for the label-safe path.
    """
    prepare_kwargs.setdefault("reconstruct", False)
    prepare_kwargs.setdefault("minimize", False)
    text = _read(path_or_text)
    pa = prepare_assembly(text, biomolecule=biomolecule, **prepare_kwargs)
    if isinstance(pa, str):
        return pa  # materialization drop reason
    # Built from BIOMT => this IS the biological assembly; mark it verified so the
    # interface gate (which guards against the WRONG oligomeric state) admits it.
    pa.report.assembly_is_asu = True
    # `build_assembly` materializes model 1 only, so the re-prepared assembly's
    # report sees a single model — carry the SOURCE model count forward so a
    # multi-model (NMR) input still trips the `multiple_models` hazard and is not
    # silently exported from one ensemble member (codex).
    pa.report.n_models = max(pa.report.n_models, _count_models(text))
    # Source-derived record id (the temp PDB is coordinate-only, so the default id
    # would collide across distinct inputs) (codex).
    record_id = _source_record_id(path_or_text)
    from .supervision import build_complex_supervision_examples

    return build_complex_supervision_examples(
        pa.structure,
        prep_report=pa.report,
        min_coverage=min_coverage,
        profile=profile,
        mask_untrustworthy_coords=mask_untrustworthy_coords,
        record_id=record_id,
    )


def _count_models(text: str) -> int:
    """Number of MODEL records in PDB text (0/1 → single model)."""
    return sum(1 for line in text.splitlines() if line.startswith("MODEL "))


def _source_record_id(path_or_text) -> Optional[str]:
    """A stable record id from the source path stem; None for inline text."""
    s = str(path_or_text)
    if "\n" in s or s.startswith(("ATOM", "HEADER", "REMARK")):
        return None
    stem = os.path.splitext(os.path.basename(s))[0]
    return f"{stem}:assembly" if stem else None


def _op_matrix(op):
    """(R 3x3, t 3) from a REMARK 350 3x4 row-major operator."""
    r = np.array([[op[i][j] for j in range(3)] for i in range(3)], dtype=np.float64)
    t = np.array([op[i][3] for i in range(3)], dtype=np.float64)
    return r, t


def _is_identity(r, t):
    return np.allclose(r, np.eye(3), atol=_OP_DEDUP_TOL) and np.allclose(t, 0.0, atol=_OP_DEDUP_TOL)


def _dedup_operators(operators):
    """Drop operators whose (R, t) duplicate an earlier one (keep first).

    Returns ``(orig_index, R, t)`` — ``orig_index`` is the 0-based position in the
    block's REMARK 350 operator list, preserved so provenance maps an assembled
    chain back to the deposited BIOMT record despite dedup/sort reordering.
    """
    kept = []
    for idx, op in enumerate(operators):
        r, t = _op_matrix(op)
        if any(np.allclose(r, kr, atol=_OP_DEDUP_TOL) and np.allclose(t, kt, atol=_OP_DEDUP_TOL)
               for _i, kr, kt in kept):
            continue
        kept.append((idx, r, t))
    return kept


def _atom_lines_for_chains(text, chains):
    """ATOM/HETATM record lines whose chain id is in `chains` (model 1 only)."""
    wanted = set(chains)
    out, in_model = [], True
    for line in text.splitlines():
        rec = line[:6]
        if rec == "MODEL ":
            # Only the first model; stop collecting after ENDMDL of model 1.
            in_model = line.split()[1] == "1" if len(line.split()) > 1 else True
        elif rec == "ENDMDL":
            in_model = False
        elif in_model and rec in ("ATOM  ", "HETATM"):
            cid = line[_CHAIN_COL] if len(line) > _CHAIN_COL else " "
            if cid in wanted or (cid == " " and "" in wanted):
                out.append(line)
    return out


def _transform_line(line, r, t, new_chain, serial):
    """Apply (R, t) to a PDB ATOM line's xyz, set its chain id, and renumber its
    atom serial (each copy needs unique serials for a valid, re-loadable PDB)."""
    xyz = np.array([float(line[_X]), float(line[_Y]), float(line[_Z])])
    nx, ny, nz = r @ xyz + t
    line = line.ljust(80)
    body = (
        line[:_SERIAL.start] + f"{serial:5d}" + line[_SERIAL.stop:_CHAIN_COL]
        + new_chain + line[_CHAIN_COL + 1:30]
        + f"{nx:8.3f}{ny:8.3f}{nz:8.3f}" + line[54:]
    )
    return body.rstrip()


# --- mmCIF emission (for assemblies PDB can't represent: >62 chains / >99999
# atoms / coords beyond ±9999.999) -------------------------------------------

# PDB ATOM/HETATM fixed columns (0-based) for the fields mmCIF needs.
_ATOM_NAME = slice(12, 16)
_ALTLOC = 16
_RESNAME = slice(17, 20)
_RESSEQ = slice(22, 26)
_ICODE = 26
_OCC = slice(54, 60)
_BFAC = slice(60, 66)
_ELEM = slice(76, 78)

#: mmCIF column order for the `_atom_site` loop.
_CIF_COLUMNS = [
    "group_PDB", "id", "type_symbol", "label_atom_id", "label_alt_id",
    "label_comp_id", "label_asym_id", "label_seq_id", "pdbx_PDB_ins_code",
    "Cartn_x", "Cartn_y", "Cartn_z", "occupancy", "B_iso_or_equiv",
    "auth_seq_id", "auth_asym_id", "pdbx_PDB_model_num",
]


def _cif_token(value: str) -> str:
    """One mmCIF data value: ``.`` for empty, quoted if it contains whitespace or
    a quote, else the bare token. (mmCIF is whitespace-delimited.)"""
    if value is None or value == "":
        return "."
    if any(c.isspace() for c in value) or "'" in value or '"' in value:
        q = '"' if "'" in value and '"' not in value else "'"
        return f"{q}{value}{q}"
    return value


def _infer_element(atom_field: str) -> str:
    """Element from the RAW 4-char PDB atom-name field (cols 13-16) when the
    element column is blank — using the PDB column alignment that disambiguates a
    1-letter element from a 2-letter one (codex):

    - col 13 (index 0) blank  -> 1-letter element in col 14, e.g. ``" CA "`` =
      alpha-carbon -> ``C`` (NOT calcium).
    - col 13 a digit          -> a numbered hydrogen, e.g. ``"1HG1"`` -> ``H``.
    - col 13 a letter         -> a 2-letter element, e.g. ``"CA  "`` = calcium ->
      ``CA``, ``"FE  "`` -> ``FE``.
    """
    s = atom_field or ""
    if not s or s[0] == " ":
        t = s.strip()
        return t[0].upper() if t and t[0].isalpha() else "X"
    if s[0].isdigit():
        return "H"
    return s[:2].strip().upper() or "X"


def _atom_site_row(line, r, t, asym_id, serial):
    """One mmCIF `_atom_site` row from a transformed PDB ATOM/HETATM line."""
    rec = line[:6].strip()  # ATOM | HETATM
    name_field = line[_ATOM_NAME]  # raw 4-char field (alignment matters for element)
    name = name_field.strip()
    alt = line[_ALTLOC].strip()
    resname = line[_RESNAME].strip()
    resseq = line[_RESSEQ].strip()
    icode = line[_ICODE].strip() if len(line) > _ICODE else ""
    elem = (line[_ELEM].strip() if len(line) >= 78 else "") or _infer_element(name_field)
    occ = line[_OCC].strip() if len(line) >= 60 else ""
    bfac = line[_BFAC].strip() if len(line) >= 66 else ""
    xyz = np.array([float(line[_X]), float(line[_Y]), float(line[_Z])])
    nx, ny, nz = r @ xyz + t
    # label_seq_id: integer for ATOM polymer rows; "." for HETATM (ligand/water
    # have no polymer sequence position — `= resseq` would be wrong) (codex).
    label_seq = resseq if rec == "ATOM" else "."
    fields = [
        rec, str(serial), _cif_token(elem), _cif_token(name), _cif_token(alt),
        _cif_token(resname), _cif_token(asym_id), label_seq, _cif_token(icode),
        f"{nx:.3f}", f"{ny:.3f}", f"{nz:.3f}",
        occ or "1.00", bfac or "0.00",
        resseq, _cif_token(asym_id), "1",
    ]
    return " ".join(fields)


def _emit_mmcif(copies, cids):
    """The mmCIF text (a single `_atom_site` loop) for the assembled copies."""
    rows = []
    serial = 0
    for (r, t, _ident, _src, _op, lines, _m), cid in zip(copies, cids):
        for ln in lines:
            serial += 1
            rows.append(_atom_site_row(ln, r, t, cid, serial))
    header = ["data_assembly", "#", "loop_"] + [f"_atom_site.{c}" for c in _CIF_COLUMNS]
    return "\n".join(header + rows) + "\n#\n"


def build_assembly(
    path_or_text: Union[str, os.PathLike], *, biomolecule: int = 1, prefer_mmcif: bool = False
) -> Union[BuiltAssembly, str]:
    """Build biomolecule ``biomolecule`` from a PDB's REMARK 350 BIOMT operators.

    Returns a :class:`BuiltAssembly` (PDB-backed when it fits PDB's limits, else
    mmCIF — see :attr:`BuiltAssembly.format`), or a drop-reason string for the only
    genuine "can't build" cases: ``"no_assembly_metadata"`` (no usable REMARK 350)
    or ``"biomolecule_not_found"``. Size is never a reason to drop — large
    assemblies (capsids, big oligomers) are emitted as mmCIF. Never raises on these.
    """
    text = _read(path_or_text)
    bios = parse_remark_350(text)
    if not bios:
        return "no_assembly_metadata"
    bio = next((b for b in bios if b.id == biomolecule), None)
    if bio is None or not bio.operators:
        return "biomolecule_not_found"

    # Per-block (chains, operators): each block's operators apply ONLY to its own
    # chains, not all-to-all (codex). `bio.blocks` preserves the association; older
    # single-block records collapse to one block via the flattened views.
    blocks = bio.blocks or [OperatorBlock(chains=bio.chains, operators=bio.operators)]

    chain_lines: dict = {}
    candidates = []  # (ident, src, op_idx, r, t) across ALL blocks
    n_ops_total = 0
    for blk in blocks:
        ops = _dedup_operators(blk.operators)
        n_ops_total += len(ops)
        present = []
        for c in blk.chains:
            if c not in chain_lines:
                ls = _atom_lines_for_chains(text, [c])
                if ls:
                    chain_lines[c] = ls
            if c in chain_lines:
                present.append(c)
        for op_idx, r, t in ops:
            ident = _is_identity(r, t)
            for src in present:
                candidates.append((ident, src, op_idx, r, t))
    if not chain_lines:
        return "no_assembly_metadata"

    # Place ALL identity copies first (across every block), THEN expansions, so the
    # redundant-overlap skip never drops a real ASU identity copy in favour of an
    # earlier block's expansion that happened to land on it (codex). The overlap
    # check compares against ALL placed copies of ANY chain (an operator can map
    # one listed chain onto another's deposited position); the shape guard means
    # only identical-size chains can coincide. Collected BEFORE the PDB-limit check
    # so redundant operators that collapse don't trip the limit (codex).
    candidates.sort(key=lambda c: not c[0])  # identities (ident=True) first
    placed = []  # all placed copies' coords (any chain)
    copies = []  # (r, t, ident, src, op_idx, lines, moved)
    for ident, src, op_idx, r, t in candidates:
        lines = chain_lines[src]
        coords = np.array([[float(l[_X]), float(l[_Y]), float(l[_Z])] for l in lines])
        moved = coords @ r.T + t
        if any(
            prev.shape == moved.shape
            and np.sqrt(((prev - moved) ** 2).sum(axis=1).mean()) < _OVERLAP_RMSD_TOL
            for prev in placed
        ):
            continue
        placed.append(moved)
        copies.append((r, t, ident, src, op_idx, lines, moved))

    # Choose the output FORMAT. PDB caps at 99,999 atom serials, ±9999.999 Å coords,
    # and a finite chain-id space (62 alphabet + a preserved blank→space); an
    # assembly exceeding any of these is emitted as mmCIF (no such limits) — size is
    # never a reason to drop now. The chain-id capacity is checked EXACTLY by trying
    # the PDB id assignment (which returns None on exhaustion), so a blank-chain
    # identity + a full 62-letter alphabet (63 chains) still fits PDB (codex).
    n_atoms = sum(len(lines) for *_x, lines, _m in copies)
    coords_overflow = any(
        _m.size and (_m.min() < _PDB_COORD_MIN or _m.max() > _PDB_COORD_MAX) for *_x, _m in copies
    )
    pdb_cids = None
    if not prefer_mmcif and n_atoms <= _MAX_PDB_SERIAL and not coords_overflow:
        pdb_cids = _assign_pdb_chain_ids(copies)  # None if it runs out of legal ids

    if pdb_cids is not None:
        cids = pdb_cids
        emitted, serial = [], 0
        for (r, t, _i, _s, _o, lines, _m), cid in zip(copies, cids):
            for ln in lines:
                serial += 1
                emitted.append(_transform_line(ln, r, t, cid, serial))
        text, fmt = "\n".join(emitted) + "\nEND\n", "pdb"
    else:
        cids = _assign_mmcif_chain_ids(copies)
        text, fmt = _emit_mmcif(copies, cids), "mmcif"

    provenance = [
        AssemblyChain(cid, src, op_idx, ident)
        for (_r, _t, ident, src, op_idx, _ln, _m), cid in zip(copies, cids)
    ]
    return BuiltAssembly(
        text=text,
        format=fmt,
        chains=provenance,
        n_operators=n_ops_total,
        n_source_chains=len(chain_lines),
        biomolecule_id=biomolecule,
    )


def _assign_pdb_chain_ids(copies):
    """Two-pass legal single-char PDB chain ids: identity copies claim their
    deposited id (letter, or blank→space), expansions get the next free letter.
    Returns ``None`` if the legal id space is exhausted (caller falls to mmCIF) —
    an EXACT capacity check, so a blank-chain identity (space) plus a full 62-letter
    alphabet (63 chains) still fits."""
    used: set = set()
    cids = [None] * len(copies)
    for i, (_r, _t, ident, src, _op, _ln, _m) in enumerate(copies):
        deposited = src if src else " "
        if ident and (deposited in _CHAIN_ALPHABET or deposited == " ") and deposited not in used:
            cids[i] = deposited
            used.add(deposited)
    free = (ch for ch in _CHAIN_ALPHABET if ch not in used)
    for i in range(len(copies)):
        if cids[i] is None:
            cids[i] = next(free, None)
            if cids[i] is None:
                return None  # ran out of legal PDB chain ids -> mmCIF
    return cids


def _assign_mmcif_chain_ids(copies):
    """Multi-char mmCIF chain ids (no 62-char limit): identity copies preserve the
    deposited id (blank → ``"A"`` — mmCIF label_asym_id can't be empty), expansions
    get a unique ``{source}-{n}`` token."""
    used: set = set()
    cids = [None] * len(copies)
    for i, (_r, _t, ident, src, _op, _ln, _m) in enumerate(copies):
        if ident and src and src not in used:
            cids[i] = src
            used.add(src)
    counter: dict = {}
    for i in range(len(copies)):
        if cids[i] is None:
            base = copies[i][3] or "A"  # src; blank -> "A"
            k = counter.get(base, 1)
            cid = f"{base}-{k}"
            while cid in used:
                k += 1
                cid = f"{base}-{k}"
            counter[base] = k + 1
            cids[i] = cid
            used.add(cid)
    return cids


def _read(path_or_text) -> str:
    s = str(path_or_text)
    if "\n" in s or s.startswith(("ATOM", "HEADER", "REMARK")):
        return s
    with io.open(s, "r") as fh:
        return fh.read()
